# Generated by Django 3.1.4 on 2020-12-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField()),
            ],
        ),
    ]
