# Generated by Django 3.1.4 on 2020-12-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='routes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.PositiveSmallIntegerField()),
                ('city_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_b', to='user_system.locations')),
                ('city_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_system.locations')),
            ],
        ),
    ]
