# Generated by Django 3.1.4 on 2020-12-23 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0003_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='city_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_a', to='user_system.locations'),
        ),
    ]
