# Generated by Django 3.1.4 on 2020-12-23 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0004_auto_20201223_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='world_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField()),
                ('data', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='drones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.BooleanField()),
                ('job_start_time', models.TimeField(null=True)),
                ('job_duration', models.PositiveIntegerField(null=True)),
                ('job_finish_time', models.TimeField(null=True)),
                ('destination_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_id', to='user_system.locations')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_system.locations')),
                ('origin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_id', to='user_system.locations')),
                ('route_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user_system.routes')),
                ('user_id', models.ForeignKey(null=True, on_delete=models.SET(0), to='user_system.users')),
            ],
        ),
    ]
