# Generated by Django 3.1.4 on 2020-12-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0005_drones_world_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drones',
            name='destination_id',
        ),
        migrations.RemoveField(
            model_name='drones',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='drones',
            name='origin_id',
        ),
        migrations.RemoveField(
            model_name='drones',
            name='route_id',
        ),
        migrations.RemoveField(
            model_name='drones',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='world_data',
        ),
        migrations.DeleteModel(
            name='drones',
        ),
    ]
