# Generated by Django 3.1.4 on 2020-12-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0007_delete_routes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='locations',
        ),
    ]
