# Generated by Django 3.1.4 on 2020-12-26 17:35

from django.db import migrations


def populate_drones(apps, schema_editor):
    drones = apps.get_model('drone_system', 'drones')
    locations = apps.get_model('drone_system', 'locations')

    for _ in range(0, 22):
        drone = drones(location_id=(locations.objects.get(id=1)).pk, job=False)
        drone.save()

    for _ in range(0, 8):
        drone = drones(location_id=(locations.objects.get(id=2)).pk, job=False)
        drone.save()

    for _ in range(0, 11):
        drone = drones(location_id=(locations.objects.get(id=3)).pk, job=False)
        drone.save()

    for _ in range(0, 19):
        drone = drones(location_id=(locations.objects.get(id=4)).pk, job=False)
        drone.save()

    for _ in range(0, 15):
        drone = drones(location_id=(locations.objects.get(id=5)).pk, job=False)
        drone.save()

    for _ in range(0, 18):
        drone = drones(location_id=(locations.objects.get(id=6)).pk, job=False)
        drone.save()

    for _ in range(0, 7):
        drone = drones(location_id=(locations.objects.get(id=7)).pk, job=False)
        drone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('drone_system', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(populate_drones),
    ]


