# Generated by Django 3.1.4 on 2020-12-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.TextField()),
            ],
        ),
    ]
