# Generated by Django 3.1.4 on 2020-12-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0008_delete_locations'),
        ('drone_system', '0002_auto_20201226_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='future_bookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_start_time', models.TimeField()),
                ('job_duration', models.PositiveIntegerField(null=True)),
                ('job_finish_time', models.DateTimeField(null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='drone_system.locations')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone_system.drones')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='drone_system.locations')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drone_system.routes')),
                ('user', models.ForeignKey(on_delete=models.SET(0), to='user_system.users')),
            ],
        ),
    ]
