# Generated by Django 3.1.4 on 2020-12-29 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_system', '0002_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='drone_system.cities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='intracity',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
