# Generated by Django 3.1.4 on 2020-12-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone_system', '0003_auto_20201229_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='intracity',
            new_name='intercity',
        ),
    ]
