# Generated by Django 3.1.4 on 2020-12-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0008_delete_locations'),
        ('drone_system', '0004_auto_20201229_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='bases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.BooleanField()),
                ('job_start_time', models.DateTimeField(null=True)),
                ('job_duration', models.PositiveIntegerField(null=True)),
                ('job_finish_time', models.DateTimeField(null=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_origin', to='drone_system.locations')),
                ('future_booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drone_system.future_bookings')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drone_system.locations')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_destination', to='drone_system.locations')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='drone_system.routes')),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(0), to='user_system.users')),
            ],
        ),
    ]
