# Generated by Django 3.1.4 on 2020-12-30 18:38

from django.db import migrations


def populate_bases(apps, schema_editor):
    bases = apps.get_model('drone_system', 'bases')

    for _ in range(0, 12):
        base = bases(location_id=1, job=False)
        base.save()

    for _ in range(0, 6):
        base = bases(location_id=2, job=False)
        base.save()

    for _ in range(0, 8):
        base = bases(location_id=3, job=False)
        base.save()

    for _ in range(0, 7):
        base = bases(location_id=4, job=False)
        base.save()

    for _ in range(0, 7):
        base = bases(location_id=5, job=False)
        base.save()

    for _ in range(0, 10):
        base = bases(location_id=6, job=False)
        base.save()

    for _ in range(0, 6):
        base = bases(location_id=7, job=False)
        base.save()

    for _ in range(0, 4):
        base = bases(location_id=8, job=False)
        base.save()

    for _ in range(0, 6):
        base = bases(location_id=9, job=False)
        base.save()

    for _ in range(0, 4):
        base = bases(location_id=10, job=False)
        base.save()

    for _ in range(0, 10):
        base = bases(location_id=11, job=False)
        base.save()

    for _ in range(0, 8):
        base = bases(location_id=12, job=False)
        base.save()

    for _ in range(0, 7):
        base = bases(location_id=13, job=False)
        base.save()

    for _ in range(0, 5):
        base = bases(location_id=14, job=False)
        base.save()

    for _ in range(0, 8):
        base = bases(location_id=15, job=False)
        base.save()

    for _ in range(0, 6):
        base = bases(location_id=16, job=False)
        base.save()

    for _ in range(0, 5):
        base = bases(location_id=17, job=False)
        base.save()

    for _ in range(0, 3):
        base = bases(location_id=18, job=False)
        base.save()

    for _ in range(0, 6):
        base = bases(location_id=19, job=False)
        base.save()

    for _ in range(0, 4):
        base = bases(location_id=20, job=False)
        base.save()

    for _ in range(0, 4):
        base = bases(location_id=21, job=False)
        base.save()

    for _ in range(0, 4):
        base = bases(location_id=22, job=False)
        base.save()

    for _ in range(0, 7):
        base = bases(location_id=23, job=False)
        base.save()

    for _ in range(0, 4):
        base = bases(location_id=24, job=False)
        base.save()

    for _ in range(0, 5):
        base = bases(location_id=25, job=False)
        base.save()

    for _ in range(0, 4):
        base = bases(location_id=26, job=False)
        base.save()


class Migration(migrations.Migration):

    dependencies = [
        ('drone_system', '0005_bases'),
    ]

    operations = [
        migrations.RunPython(populate_bases),
    ]
